branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/
before_install:
 - . port/travis-ci/travis-functions.sh
 - init_travis
 - wrapper init_env_vars
 - wrapper init_perl
 - wrapper init_apt
 - wrapper install_non_perl_dependencies
 - wrapper install_perl_testonly_dependencies
 - wrapper install_old_perl_dependencies
 - wrapper install_webserver_dependencies
 - wrapper install_selenium
install:
 - wrapper install_perl_dependencies
before_script:
 - wrapper init_cgi_config
 - wrapper fix_cgis
 - wrapper init_webserver_config
 - wrapper start_webserver
 - wrapper start_xserver
 - wrapper init_webserver_environment
 - wrapper start_selenium
 - wrapper init_data
script:
 - perl Makefile.PL && make test HARNESS_OPTIONS=j4
after_script:
 - make distcheck

language: perl
dist: trusty
arch:
  - arm64
matrix:
  include:
## XXX system perl does not work yet --- missing packages in mydebs
#    - dist: xenial
#      perl: 5.22
#      env: USE_MODPERL=1 USE_SYSTEM_PERL=1
    - dist: xenial
      perl: 5.24
      env: BBBIKE_TEST_SKIP_MODPERL=1 BBBIKE_TEST_GUI=1
    - dist: bionic
      perl: 5.26
      env: BBBIKE_TEST_SKIP_MODPERL=1
## XXX does not work yet --- Geo::Proj4 does not build
#    - dist: focal
#      perl: 5.32
#      env: BBBIKE_TEST_SKIP_MODPERL=1

### Fastest results (8 min)
#    - perl: "5.18"
#      env: USE_MODPERL=1 USE_SYSTEM_PERL=1
#      dist: trusty
### Also fast
#    - perl: "5.22"
#      env: USE_MODPERL=1 USE_SYSTEM_PERL=1
#      dist: xenial
### Slowest both, should also be in the first group
##    - perl: "5.20-shrplib"
##      env: USE_MODPERL=1
##      dist: precise
#    - perl: "5.20-shrplib"
#      env: USE_MODPERL=1
### Perl with no dot in @INC
#    - perl: "5.26"
#      env: BBBIKE_TEST_SKIP_MODPERL=1 BBBIKE_TEST_GUI=1
#      dist: xenial
#    - perl: "5.30"
#      env: BBBIKE_TEST_SKIP_MODPERL=1
#      dist: bionic
#    - perl: "5.18"
#      env: BBBIKE_TEST_SKIP_MODPERL=1 BBBIKE_TEST_GUI=1 BBBIKE_TEST_SKIP_MAPSERVER=0
#    - perl: "5.10"
#      env: BBBIKE_TEST_SKIP_MODPERL=1
#    - perl: "5.8"
#      env: BBBIKE_TEST_SKIP_MODPERL=1
##    - perl: "5.14"
##      env: USE_MODPERL=1 USE_SYSTEM_PERL=1
##      dist: precise
#    - perl: "5.24"
#      env: BBBIKE_TEST_SKIP_MODPERL=1
#  allow_failures:
### exit code is 0, but builds are mysteriously failing
#    - dist: precise
