before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq freebsd-buildutils libproj-dev
language: perl
perl:
  - "5.18"
  - "5.14"
  - "5.10"
## disabled because of DBD::XBase issues, see https://rt.cpan.org/Ticket/Display.html?id=88873
#  - "5.8"
